### ISSUE TITLE
Hitting secondary rate limits

### ISSUE THREAD

**Issue by richardlau** [nodejs/nodejs-dependency-vuln-assessments#80]
e.g. https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/3341823626

https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/3341823626/jobs/5533421701
```
ℹ  info      Fetching all issues with title "CVE-2022-3358 (OpenSSL) found on main"
Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
✖  fatal     HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. 
    at /home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:6038:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createAnIssue (/home/runner/work/_actions/dblock/create-a-github-issue/v3/dist/index.js:37939:[32](https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/3341823626/jobs/5533421701#step:3:33))
```

**Comment by RafaelGSS** [comment]
@facutuesca

**Comment by mhdawson** [comment]
@richardlau that might be because with your update to generate the list of streams we now do all lines at the same time, versus having them spread out a bit? I know that I had scheduled at least some of them to run several hours appart.

Is there some way that we can lauch the jobs for each version spaced out in time ?

**Comment by facutuesca** [comment]
@richardlau @mhdawson I created a PR to try to fix it: https://github.com/nodejs/nodejs-dependency-vuln-assessments/pull/81

**Comment by mhdawson** [comment]
@richardlau, @facutuesca can you take a look. I `think` the job I started to test looked ok, but would be good to have a few other people confirm

**Comment by facutuesca** [comment]
The job looks good to me (no rate limits failures). Looking at [Github's docs on secondary rate limits](https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits):
> Make requests for a single user or client ID serially. Do not make requests for a single user or client ID concurrently.

The merged PR should have taken care of it by running each action/step sequentially instead of in parallel

**Comment by mhdawson** [comment]
k, going to close out this issue.
